# Generated by Django 4.0.5 on 2022-07-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='equipo',
            field=models.CharField(default='Team Involved', max_length=40),
        ),
        migrations.AddField(
            model_name='blog',
            name='jugador_actual',
            field=models.CharField(default='Player/s Involved', max_length=40),
        ),
    ]
